INHERIT: ./common/mkdocs_base.yml

site_name: sasano8
site_description: sasano8's portfolio

# repo_name: CodingRule
repo_url: https://github.com/sasano8/CodingRule
# edit_uri: ""
site_url: https://sasano8.github.io/CodingRule/

nav:
  - はじめに: "index.md"
  - 標準仕様: "standard_spec.md"
  - セキュリティ:
    - 権限: "security/auth.md"
    - オシント: "security/osint.md"
  - アーキテクチャ: "architecture.md"
  - データベース: "database.md"
  - ビジュアライズ: "visualization.md"
  - テスト: "test.md"
  - プログラム言語:
    - VBA: "program/vba.md"
    - Python: "program/python.md"
    - JavaScript: "program/javascript.md"
    - SQL: "program/sql.md"
    - 構文解析: "program/parsing.md"
  - 要件定義:
    - マネジメント: "requirements/management.md"
    - 機能要件: "requirements/functional.md"
    - 非機能要件: "requirements/non_functional.md"
    - 設計: "requirements/design.md"
  - awasome api: "awasome_api.md"
  - 数学: "math.md"
  - tools:
    - tmux: "tools/tmux.md"
