site_name: sasano8
site_description: sasano8's portfolio
# site_url: https://www.python-httpx.org/

theme:
  name: "material"
  language: "ja"

# repo_name: encode/httpx
# repo_url: https://github.com/encode/httpx/
# edit_uri: ""

nav:
  - はじめに: "index.md"
  - 標準使用: "standard_spec.md"
  - セキュリティ: "security.md"
  - アーキテクチャ: "architecture.md"
  - データベース: "database.md"
  - ビジュアライズ: "visualization.md"
  - テスト: "test.md"
  - プログラム言語 - VBA: "program_vba.md"
  - プログラム言語 - Python: "program_python.md"
  - プログラム言語 - Javascript: "program_javascript.md"
  - プログラム言語 - SQL: "program_sql.md"
  - 要件定義: "requirement_definition.md"
  - awasome api: "awasome_api.md"

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list

extra_css:
  - css/custom.css

# extra_javascript:
  # - "js/chat.js"
  # - "js/sidecar-1.5.0.js"

